### ISSUE TITLE
Lambda authorizers

### ISSUE THREAD

**Issue by lllama** [terraform-aws-modules/terraform-aws-appsync#19]
Lambda authorizers would be a good feature. Sadly this isn't available in the aws provider. See https://github.com/hashicorp/terraform-provider-aws/issues/20644

I'm opening this for tracking purposes - please feel free to close if that's not appropriate.

**Comment by antonbabenko** [comment]
Hi @lllama !

It is ok to have issues like this. I have labeled it with `upstream blocker`.

**Comment by michaelhelmick** [comment]
Looks like https://github.com/hashicorp/terraform-provider-aws/issues/20644 was merged 4 days ago!

**Comment by antonbabenko** [comment]
Great! Please make a PR with the required changes (code, example, docs).
