### ISSUE TITLE
Module tries to create service role when one is provided

### ISSUE THREAD

**Issue by kyeotic** [terraform-aws-modules/terraform-aws-appsync#21]
## Description

Using 

```hcl
  datasources = {
    GQL_Lambda = {
      type             = "AWS_LAMBDA"
      function_arn     = aws_lambda_function.api.arn
      service_role_arn = aws_iam_role.appsync.arn
    }
  }
  ```
  
I expect it to use the role I provided and not to create one.
  
This isn't exactly documented, but it [looks like](https://github.com/terraform-aws-modules/terraform-aws-appsync/blob/af1fe4f394b6914203cbff1d5118378bc163b01e/main.tf#L98) providing this value should stop it from making its own role, but thats not the case.

Is it possible to provide the role here, or will this module always make its own?

The other issue i have is that the name doesn't use the `terraform.workspace`, so it conflicts with other deployments in the same account.

## Versions
 - Terraform: 1.0.10
 - Provider(s):
 ```
 + provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/newrelic/newrelic v2.9.0
```
 - Module: latest

**Comment by antonbabenko** [comment]
I could not reproduce this one.

The module should create one or use the one that was provided.
