### ISSUE TITLE
Looking to add support for specify a domain for AppSync

### ISSUE THREAD

**Issue by stevewillard** [terraform-aws-modules/terraform-aws-appsync#23]
Hi there. It looks like AWS recently added support for custom domains on your AppSync APIs: https://aws.amazon.com/blogs/mobile/introducing-custom-domain-names-for-aws-appsync-apis/

It would be great if those module supported that configuration.

Thanks!

**Comment by antonbabenko** [comment]
Hi Steve,

This feature is not yet available in [Terraform AWS provider](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md).

**Comment by svenlito** [comment]
Here is the feature request on the provider repo https://github.com/hashicorp/terraform-provider-aws/issues/22088

**Comment by stevewillard** [comment]
Oh great - it looks like this was added to the provider repo. Does this package need to be updated to take advantage of those updates, or is the configuration (somehow) available through this module?

**Comment by antonbabenko** [comment]
@stevewillard Yes, this module has to be updated to support new resources introduced at https://github.com/hashicorp/terraform-provider-aws/pull/22487.

PR is welcome.
