### ISSUE TITLE
Missing account id in generated arns for IAM policies

### ISSUE THREAD

**Issue by shannoncolavita** [terraform-aws-modules/terraform-aws-appsync#3]
Hi Just wondering if the account id is going to be added to the generated IAM policies? ie in iam.tf
ln 22  resources = [format("arn:aws:dynamodb:%v::table/%v", v.region, v.table_name)]

only region & table name are currently substituted

Thanks
Shannon

**Comment by antonbabenko** [comment]
Hi Shannon,

In this case, account id is not going to be added to the service role, but I think you are right that it should also take into account the current (or provided) AWS account ID to allow cross-account access to DynamoDB tables.

Pull-request is welcome.

**Comment by antonbabenko** [comment]
Thanks a lot for opening this issue.

I have just fixed it and [v0.5.0](https://github.com/terraform-aws-modules/terraform-aws-appsync/releases/v0.5.0) has been just released.
