### ISSUE TITLE
app_id_client_regex configuration for user_pool_config

### ISSUE THREAD

**Issue by x539** [terraform-aws-modules/terraform-aws-appsync#35]
https://github.com/terraform-aws-modules/terraform-aws-appsync/blob/c41b990fcb0a48771f64bac856453274f574fedd/main.tf#L54
https://github.com/terraform-aws-modules/terraform-aws-appsync/blob/c41b990fcb0a48771f64bac856453274f574fedd/main.tf#L55
This should propably be user_pool_config not openid_connect_config:

```tf
      default_action      = var.user_pool_config["default_action"]
      user_pool_id        = var.user_pool_config["user_pool_id"]
      app_id_client_regex = lookup(var.user_pool_config, "app_id_client_regex", null)
      aws_region          = lookup(var.user_pool_config, "aws_region", null)
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.5.2 :tada:
