### ISSUE TITLE
Pass in 'ignore_changes'

### ISSUE THREAD

**Issue by schneider10** [terraform-aws-modules/terraform-aws-appsync#36]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality
  
 Yes, v1 or earlier

## Is your request related to a problem? Please describe.

Yes, essentially AWS will alter my lambda resolver service policy after every apply so I consistently have `Plan: 1 to add, 2 to change, 1 to destroy.` I'd like to be able to ignore these modifications so they don't show up on every plan/apply.

## Describe the solution you'd like.

I would love it if we could pass in some argument to ignore changes specific to an iam policy or role. 

## Describe alternatives you've considered.

Not using this module - writing this using resources instead so I can ignore changes when I'd like. Waiting for terraform to build a feature that allows me to pass in overrides when defining the module.

**Comment by antonbabenko** [comment]
There is no way to specify variables inside of meta-arguments like `ignore_changes`, so this module can't be updated to do what you want. See these issues for more:
https://github.com/hashicorp/terraform/issues/3116
https://github.com/hashicorp/terraform/issues/21546
