### ISSUE TITLE
Error creating appsync resources with  ConcurrentModificationException: Schema is currently being altered

### ISSUE THREAD

**Issue by cshivashankar** [terraform-aws-modules/terraform-aws-appsync#4]
Hi,

I am trying to create resources using the module and I get the following error sometimes ,
```
Error: error creating Appsync API Key: ConcurrentModificationException: Schema is currently being altered, please wait until that is complete.
```
This error looks intermittent and the issue doesnt appear when we trigger the same command after 30 - 60 seconds.
I did try adding `depends_on` constraint but that also did not solve the issue.
Has any one faced this issue before ?
.I tried adding support for functions and there were intermittent issues for functions too with similar error
```
Error: Error creating AppSync Function: ConcurrentModificationException: Schema is currently being altered, please wait until that is complete.
```
There is a mention of this error in the document https://docs.aws.amazon.com/appsync/latest/APIReference/API_UpdateGraphqlApi.html but no clear instruction on how to get around it ?

Terraform code to reproduce this error is similar to https://github.com/terraform-aws-modules/terraform-aws-appsync/tree/master/examples/complete
Add more datasources, resolvers in the file.

Has anyone faced this issue before ?

**Comment by antonbabenko** [comment]
Hi @cshivashankar !

Thanks for opening this issue. I don't think I personally saw this error with my projects or when I use the example code so I believe the workaround is to look into the simplification of data sources and resolvers configurations.

Could you share your complete configuration code for this module with replaced sensitive values? I want to see if I can do anything in the code to make this work.

As a more permanent fix, I would recommend opening an issue in [Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws). There are several similar issues in other resources, for eg, https://github.com/hashicorp/terraform-provider-aws/issues/14541 .

**Comment by antonbabenko** [comment]
I have just rerun the same example 5 times and just once I got the error `ConcurrentModificationException`. I am pretty sure it is a bug in Terraform AWS provider.

**Comment by cshivashankar** [comment]
Yes it is intermittent error , I think a bug needs to be created with terraform aws provider

**Comment by cshivashankar** [comment]
@antonbabenko I have raised an issue with provider , https://github.com/hashicorp/terraform-provider-aws/issues/16211
I think this issue should be solvable by reducing the parallelism in execution , but its more of  a workaround rather than actual fix .
I doubt if there there is a retry option in terraform which is also a good workaround for this problem.

Regards,
Chetan

**Comment by antonbabenko** [comment]
I agree, let's see what kind of feedback will be on that one. Thanks for opening it.

**Comment by stataraju** [comment]
use depends on but note if "C" resource depends on "B" and "B" on "A" then depends on should be used like 

for "C"  resource  ---->               depends_on = [A, B]
for "B" resource ----->               depends_on = [A]

if you specify for "C"  resource  as  -----> depends_on = [B]          then also chances will be there for getting this "Exception: Schema is currently being altered"
