### ISSUE TITLE
About JavaScript support for AppSync Resolvers

### ISSUE THREAD

**Issue by wadelicw** [terraform-aws-modules/terraform-aws-appsync#42]
In November 2022, AWS [announced JavaScript support for AppSync Resolvers](https://aws.amazon.com/blogs/aws/aws-appsync-graphql-apis-supports-javascript-resolvers/)

How can I create a function in JS, without splitting by request_template and response_template. Currently there is only ONE template for JS function. On the other hand, pipeline resolver also support JS version.

Could you please advisor how to achieve those feature, let say some work around?

Thank you very very much

**Comment by tkoenig-sz** [comment]
This is still a thing... Has anyone the skills to do this?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.7.0 :tada:
