### ISSUE TITLE
Add support for JS resolvers

### ISSUE THREAD

**Issue by juanoi** [terraform-aws-modules/terraform-aws-appsync#43]
## Is your request related to a new offering from AWS? Yes

Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? 
Yes. The functionality was introduced with version 4.47.0

## Is your request related to a problem? 
Yes, currently only VTL is supported for defining resolvers.

## Describe the solution you'd like.
Extending this module to allow using JS resolvers.

## Describe alternatives you've considered.
Creating external `aws_appsync_function ` resources referencing the API created using this module.

## Additional context
None.

**Comment by tkoenig-sz** [comment]
This is still a thing... Has anyone the skills to do this?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.7.0 :tada:
