### ISSUE TITLE
Enable JS functions

### ISSUE THREAD

**Issue by juanoi** [terraform-aws-modules/terraform-aws-appsync#48]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? 
Yes, the module currently does not support creating functions using the JS runtime.

## Describe the solution you'd like.
Adjust this module to accept `runtime` and `code` parameters to be forwarded to the internal `aws_appsync_function` resources.

## Describe alternatives you've considered.
Using VTL. Really a no-go from my perspective.

## Additional context
JS support for resolvers was recently added. This would nicely complement that new functionality.
I would be happy to submit a PR.

**Comment by GiamPy5** [comment]
https://github.com/terraform-aws-modules/terraform-aws-appsync/pull/49 :)
