### ISSUE TITLE
feat: create route53 record for custom appsync domain

### ISSUE THREAD

**Issue by jagoodhand** [terraform-aws-modules/terraform-aws-appsync#56]
## Is your request related to a problem? Please describe.

Currently the AppSync module deploys with a domain name mapping, but doesn't provide the necessary Route53 record to enable that domain to work. This can lead someone to be confused as to why the appsync api isn't available at their domain, but is working from the CloudFront distribution.

## Describe the solution you'd like.

Module should create the necessary route53 record. Currently this needs to be done using something like:

```hcl
resource "aws_route53_record" "api" {
  zone_id = var.route53_domain_zone_id
  name    = "api.${var.domain}"
  type    = "CNAME"
  ttl     = "300"
  records = [module.appsync.appsync_domain_name]
}
```

## Describe alternatives you've considered.

Update to the documentation.

## Additional context

Not sure if this is necessary, because it isn't necessarily part of AppSync, but it may make the module more complete / usable. Would require an extra variable of something like 'domain_zone_id' for the Route53 hosted zone that the record should be placed in. Alternatively, it could offer the option to create the zone if one isn't provided.

Not sure if this is really necessary, or if it fits your aim for these modules, but was thought that occurred whilst using it.

**Comment by antonbabenko** [comment]
This is by design. Route53 is not part of AppSync service, so it is not implemented as a part of this module. You have to use the resource `aws_route53_record` like you've described.
