### ISSUE TITLE
explain: dynamic references (module.aws_lambda_function2.lambda_function_arn) do not work unless you create this resource in advance

### ISSUE THREAD

**Issue by automaticgiant** [terraform-aws-modules/terraform-aws-appsync#63]
## Description

what resource needs created in advance?
every time i add the lambda data source, i get 
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/oss.appsync/iam.tf line 12, in locals:
│   12:           resources = [for _, f in ["%v", "%v:*"] : format(f, v.function_arn)]
│ 
│ This object does not have an attribute named "function_arn".
╵
╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/oss.appsync/iam.tf line 12, in locals:
│   12:           resources = [for _, f in ["%v", "%v:*"] : format(f, v.function_arn)]
│ 
│ This object does not have an attribute named "function_arn".
```
it seems like it is a known behavior, so i'm looking for clarification.
i'm able to create both modules, unless i specify the datasource.
so creating both modules (create this resource first?) without the datasource is fine but enabling yields the error.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
main

- Terraform version:
1.5.7
- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v5.60.0
+ provider registry.terraform.io/hashicorp/external v2.3.3
+ provider registry.terraform.io/hashicorp/local v2.5.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.2

**Comment by automaticgiant** [comment]
realized i had incorrectly used lambda_function_arn in the datasource map instead of function_arn

**Comment by automaticgiant** [comment]
in retrospect, i'm having zero issues with resource creation order. still curious about the comment. @antonbabenko

**Comment by antonbabenko** [comment]
I believe you could have used output named `lambda_function_arn_static` from the Lambda module instead of `lambda_function_arn`. It was added specifically for such issues.

Read more: https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/outputs.tf#L7-L10

**Comment by automaticgiant** [comment]
Hmm. That's good context. I'll add a comment to my config to switch to that if we experience issues but so far it seems premature until i ever see breakage not due to incorrect arguments. Is it possible that the failure mode alluded to by the comment was eliminated by other means? Unless there's something that comes to mind, I guess we may never know.
