### ISSUE TITLE
aws_iam_role service_role resources are not being tagged

### ISSUE THREAD

**Issue by dat-timfa** [terraform-aws-modules/terraform-aws-appsync#8]
The following resource block is missing a tagging attribute. Tagging is so used to organize infrastructure and implement policy checks based on tags.

https://github.com/terraform-aws-modules/terraform-aws-appsync/blob/master/iam.tf#L78

The other `aws_iam_role` resources include the tag attribute, I would request that this resource also includes tagging. In this case be a new pass-in attribute for something like `service_role_tags` or default to the `tags` module-level attribute.

**Comment by alexkaufman06** [comment]
Adding a tagging attribute to the resource block mentioned above would be very useful for some work I plan on doing in the near future. Wondering if the maintainers of this repo agree with the proposed changes?

**Comment by antonbabenko** [comment]
Absolutely agree. PR is welcome :)
